# Window

CELL_SIZE = 16
NUM_CELLS = 28
WIDTH = CELL_SIZE * NUM_CELLS
HEIGHT = WIDTH
UI_WIDTH = 100
UI_HEIGHT = 36
SCALE = 0.5
UI_COLOR = (150, 75, 0)
CLOCK_INTERVAL = 1 / 60


# Game

FACTORY_START_POS = 25
FACTORY_HP = 10

MINE_RESOURCES = 1000

TRUCK_COST = 10
MAX_TRUCKS = 6
TRUCK_LOAD = 5
TRUCK_TIME_TO_MOVE = 1
TRUCK_START_POS = FACTORY_START_POS - 1
TRUCK_END_POS = 3

LASER_PACK_UNITS = 10
LASER_PACK_COST = 10
LASER_DAMAGE = 1

MISIL_PACK_UNITS = 6
MISIL_PACK_COST = 10
MISIL_DAMAGE = 2

PLASMA_PACK_UNITS = 3
PLASMA_PACK_COST = 10
PLASMA_DAMAGE = 3

NUKE_PACK_UNITS = 1
NUKE_PACK_COST = 40

SHIELD_COST = 1
